Sprint 16
DzhamiRakhmetov/Tracker pull request #3
Opened 2023-08-05 16:18 UTC by DzhamiRakhmetov

2023-08-06 11:28 UTC, mmbabaev requested changes

2023-08-06 11:28 UTC, mmbabaev commented on Categories-MVVM/View/CategoriesViewController.swift
> +//        viewModel?.delegate = self
лучше удалить закомментированный код

2023-08-06 11:28 UTC, mmbabaev commented on Categories-MVVM/View/CategoriesViewController.swift
> +            self.delegate?.selectCategory(category)
это мелочь, но возможно лучше сразу вызвать метод делегата, потом dismiss. Так состояние будет изменено уже во время dismiss

2023-08-06 11:28 UTC, mmbabaev commented on Categories-MVVM/ViewModel/CategoriesViewModel.swift
> +    private var categories: TrackerCategoryStore!
1) здесь можно легко избежать форс анрапа, если инициализировать свойство, подобно делегату. 
Можно использовать и дефолтное значение
2) я бы назвал categories -> categoryStore

2023-08-06 11:28 UTC, mmbabaev commented on Categories-MVVM/ViewModel/CategoriesViewModel.swift
> +    init(delegate: CategoriesViewModelDelegate? = nil) {
`init(delegate: CategoriesViewModelDelegate, categoryStore = TrackerCategoryStore) {`
1) nil delegate не имеет смысла, можно не делать дефолтный аргумент
2) можно здесь добавить дефолтное свойство с инициализацией Store. Также Store лучше закрыть протоколом. Так код будет тестируемым

2023-08-06 11:28 UTC, mmbabaev commented on Categories-MVVM/ViewModel/CategoriesViewModel.swift
> +            print(error.localizedDescription)
лучше добавить обработку ошибки

2023-08-06 11:28 UTC, mmbabaev commented on Categories-MVVM/ViewModel/CategoriesViewModel.swift
> +    @objc optional func reloadData()
Для чего этот метод? Он не вызывается, не реализовывается. Из-за него потребовалось добавлять objc анотации

2023-08-06 11:28 UTC, mmbabaev commented on Onboarding/OnboardingPageViewController.swift
> +        if let first = controllers.first {setViewControllers([first], direction: .forward, animated: true, completion: nil)}
не нужно все пытаться уместить в одну строку, так код менее читаемый. Также здесь можно использовать guard

2023-08-06 11:28 UTC, mmbabaev commented on Onboarding/OnboardingPageViewController.swift
> +        guard let viewControllerIndex = controllers.firstIndex(of: viewController as! OnboardingViewController) else {
вроде здесь не нужен каст типа

2023-08-06 11:28 UTC, mmbabaev commented on Onboarding/OnboardingPageViewController.swift
> +           let currentIndex = controllers.firstIndex(of: currentVC as! OnboardingViewController) {
тоже каст

2023-08-06 11:28 UTC, mmbabaev commented on Onboarding/OnboardingPageViewController.swift
> +        if let currentVC = pageViewController.viewControllers?.first,
лучше использовать guard

2023-08-06 11:28 UTC, mmbabaev commented on Onboarding/OnboardingViewController.swift
> +    var backgroundImageView = UIImageView()
нет private модификаторов

2023-08-06 11:28 UTC, mmbabaev commented on Onboarding/OnboardingViewController.swift
> +        if let sceneDelegate = scene?.delegate as? SceneDelegate,
лучше использовать guard

2023-08-06 11:28 UTC, mmbabaev commented on Onboarding/OnboardingManager.swift
> +final class OnboardingManager {
лучше : 
1) не использовать static функции
2) закрыть класс протоколом
3) вынести зависимости в свойство, дать возможность передавать его извне (UserDefaults.shared)

2023-08-06 11:28 UTC, mmbabaev commented on Onboarding/OnboardingPageViewController.swift
> +class OnboardingPageViewController: UIPageViewController {
можно тоже final

2023-08-06 11:28 UTC, mmbabaev commented on Categories-MVVM/ViewModel/Assembler.swift
> +    class func setCategoriesViewController() -> CategoriesViewController {
можно использовать `static func` - это по сути `final class func`

2023-08-06 11:28 UTC, mmbabaev commented on Categories-MVVM/ViewModel/Assembler.swift
> +    class func setCategoriesViewController() -> CategoriesViewController {
setCategoriesViewController - не очень удочное название, будто мы внутри куда-то присваиваем viewController. Обычно такие методы называют: `make/create/buildViewController`

2023-08-07 10:01 UTC, DzhamiRakhmetov commented
Не до конца понял из-за чего у вас мог не запускается проект, надеюсь в этот раз все в норме

2023-08-08 09:15 UTC, mmbabaev approved these changes

2023-08-08 09:18 UTC, merged